/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemType = IDL.Variant({ 'tv' : IDL.Null, 'movie' : IDL.Null });
export const WatchlistItem = IDL.Record({
  'id' : IDL.Nat,
  'itemType' : ItemType,
});

export const idlService = IDL.Service({
  'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistItem)], ['query']),
  'toggleItem' : IDL.Func([IDL.Nat, ItemType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemType = IDL.Variant({ 'tv' : IDL.Null, 'movie' : IDL.Null });
  const WatchlistItem = IDL.Record({ 'id' : IDL.Nat, 'itemType' : ItemType });
  
  return IDL.Service({
    'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistItem)], ['query']),
    'toggleItem' : IDL.Func([IDL.Nat, ItemType], [], []),
  });
};

export const init = ({ IDL }) => { return []; };